export type Question = {
    title: string;
    url: string;
    difficulty: "easy" | "medium" | "hard";
    tag: string;
    pattern: string[];
    revision: boolean;
    solved: boolean;
    top100: boolean;
    blind75?: boolean;
    lovebabbar: boolean;
    striver: boolean;
    neetcode: boolean;
    grind75?: boolean;
    apnaCollege?: boolean;
    algoPrep?: boolean;
    arshDSASheet?: boolean;
    algoMaster?: boolean;
    instabyte?: boolean;
    leetcode?: boolean;
    geeksforgeeks?: boolean;
    interviewbit?: boolean;
    count?: number;
    interviewMemoryTrick?: string;
    companyTags?: string[];
    notes?: string;
    videoSolution?: string;
    textSolution?: string;
};
